### PR TITLE
Fix setup crash: guard None self._last_state in InsnrgSensor.state

### PR DESCRIPTION
**Pull request by QuintinHumphreys**
## Problem
`InsnrgSensor.state` unconditionally runs `self._last_state.state = self._state`. When `self._last_state` is `None` (e.g. an empty/absent reading during setup), this raises `AttributeError: 'NoneType' object has no attribute 'state'`, which aborts `async_setup_entry` (logged as "Error setting up entry INSNRG Chlorinator"). This looks like the failure reported in #2.

## Fix
Guard the assignment with a `None` check — matching the guard already present at the other two occurrences of this same line in `sensor.py` (the pH and ORP sensor classes). One-line behavioural change; no other logic touched.

## Testing
Applied against a live INSNRG chlorinator on Home Assistant 2026.6.x. The integration now sets up cleanly and all sensors (pH, ORP, set points, connection status, and the 4 timers) populate correctly.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Mattat01** [comment]
Thanks for the correction. I've merged it, but please note that there is an official INSNRG integration available through HACS.

**Comment by QuintinHumphreys** [comment]
No problem.  I configured the INSNRG integration however it doesnt expose the timer's start and finish times...  a little disappointing.

**Comment by Mattat01** [comment]
Oh, that's a shame. Have you left it as an issue? I would have thought they would update that, although they don't always do it quickly. I haven't been actively updating this repo, but you're welcome to update anything you find useful.
